"""Extensible sentence-family registry with newly authored public demo frames.

Each built-in family ships thirty templates; ``_split_templates`` assigns the
first third to train, the second to eval, and the last to holdout, so template
depth per split scales with bank size. Positive templates may use ``{cue}``,
``{value}``, ``{persona}``, and ``{organization}`` (mixed-entity adds
``{other_cue}``/``{other_value}``); hard-negative templates may use ``{cue}``,
``{negative_value}``, ``{persona}``, and ``{organization}``. Cue-free templates
must not render any configured cue surface.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class FamilyPlugin:
    name: str
    role: str
    templates: tuple[str, ...]


_REGISTRY: dict[str, FamilyPlugin] = {}


def register_family(plugin: FamilyPlugin, *, replace: bool = False) -> None:
    if plugin.name in _REGISTRY and not replace:
        raise ValueError(f"family plugin is already registered: {plugin.name}")
    if plugin.role not in {"positive", "hard_negative"}:
        raise ValueError("family plugin role must be positive or hard_negative")
    _REGISTRY[plugin.name] = plugin


def get_family(name: str) -> FamilyPlugin:
    try:
        return _REGISTRY[name]
    except KeyError as exc:
        raise ValueError(f"unknown family plugin: {name}") from exc


def registered_families() -> tuple[str, ...]:
    return tuple(sorted(_REGISTRY))


def _add(name: str, role: str, *templates: str) -> None:
    register_family(FamilyPlugin(name=name, role=role, templates=tuple(templates)))


_add(
    "narrative",
    "positive",
    "{persona} asked {organization} to correct the {cue} shown as {value}.",
    "During a routine review, {persona} confirmed that the {cue} is {value}.",
    "The note from {organization} associates {persona} with {cue} {value}.",
    "For the fictional case, {persona} supplied {value} as the {cue}.",
    "A message to {organization} says the {cue} for {persona} should read {value}.",
    "In the synthetic narrative, {persona}'s {cue} appears as {value}.",
    "{persona} wrote to {organization} because the {cue} on file, {value}, looked outdated.",
    "Staff at {organization} read back the {cue} {value} while {persona} listened.",
    "After the appointment, {persona} noticed the {cue} was recorded as {value}.",
    "The follow-up letter repeats {value} as the {cue} belonging to {persona}.",
    "{organization} archived a memo where {persona} lists the {cue} as {value}.",
    "When asked twice, {persona} repeated the same {cue}: {value}.",
    "An intake summary for {persona} carries the {cue} {value} near the top.",
    "The clerk transcribed {value} under {cue} before {persona} left the desk.",
    "{persona} disputed a typo, insisting the {cue} must be {value}.",
    "Records clerks at {organization} matched {persona} to the {cue} {value}.",
    "A short email from {persona} closes with the {cue} written as {value}.",
    "The caseworker noted that {persona} brought paperwork showing {cue} {value}.",
    "On page two, the {cue} for {persona} reads {value} in bold.",
    "{organization} verified {persona} by comparing the stored {cue} against {value}.",
    "In the interview transcript, {persona} states the {cue} plainly: {value}.",
    "The updated profile of {persona} now shows {value} in the {cue} slot.",
    "Yesterday {persona} phoned {organization} to re-confirm the {cue} {value}.",
    "A margin annotation links {persona} with the {cue} {value}.",
    "The signed form from {persona} declares {value} to be the correct {cue}.",
    "Reviewers at {organization} flagged, then accepted, the {cue} {value} for {persona}.",
    "Halfway through the note, {persona}'s {cue} is quoted as {value}.",
    "{persona} circled the {cue} on the printout, which shows {value}.",
    "The duplicate letter also gives {value} as the {cue} of {persona}.",
    "According to the summary sheet, {persona} registered the {cue} {value}.",
)
_add(
    "structural",
    "positive",
    "person={persona} | organization={organization} | {cue}={value}",
    "{cue}\t{value}\towner\t{persona}",
    '{{"subject": "{persona}", "{cue}": "{value}"}}',
    "| field | content |\n| {cue} | {value} |\n| subject | {persona} |",
    "record_owner: {persona}\nrecord_source: {organization}\n{cue}: {value}",
    "COLUMN {cue} ; VALUE {value} ; SYNTHETIC SUBJECT {persona}",
    "{cue}: {value}\nholder: {persona}\nissuer: {organization}",
    "subject={persona}; {cue}={value}; source={organization}",
    "row 14: {persona} :: {cue} :: {value}",
    "csv,{persona},{organization},{cue},{value}",
    "{cue} = {value}  # owner {persona}",
    "field: {cue}\nentry: {value}\nlinked person: {persona}",
    "L01 {persona}\nL02 {organization}\nL03 {cue} {value}",
    "key {cue} holds {value} for subject {persona}",
    "{persona} | {cue} | {value} | verified",
    "form section B - {cue}: {value} (holder {persona})",
    "YAML dump:\nperson: {persona}\n{cue}: {value}",
    "INSERT INTO demo(person, field, entry) VALUES ('{persona}', '{cue}', '{value}')",
    "ledger row - org {organization}; person {persona}; {cue} {value}",
    "{cue}/{value} attributed to {persona} by {organization}",
    "record #A: subject {persona}; attribute {cue}; content {value}",
    "grid cell [3,2] = {value} under heading {cue} for {persona}",
    "properties: owner={persona} source={organization} {cue}={value}",
    "line item: {cue} -> {value} -> {persona}",
    "TSV export: {persona}\t{organization}\t{cue}\t{value}",
    "index card for {persona}: {cue} {value}, filed by {organization}",
    "data pair ({cue}, {value}) attached to profile {persona}",
    "audit table lists {value} beneath {cue} beside {persona}",
    "spreadsheet note: {cue} column holds {value} on the {persona} row",
    "manifest line: {cue}={value} recorded for {persona} at {organization}",
)
_add(
    "ocr_noise",
    "positive",
    "Scanned line: {persona} / {cue} / {value}",
    "OCR extract from {organization}: {cue} reads {value} for {persona}.",
    "Low-quality form transcription: {cue}: {value}; name: {persona}.",
    "Page fragment for {persona} -- {cue} {value} -- end fragment.",
    "Machine-read note from {organization}: {value} follows the {cue} heading.",
    "The noisy scan ties {persona} to {cue} {value}.",
    "Blurred header, legible body: {cue} {value}, holder {persona}.",
    "Rescan requested; provisional read gives {cue} as {value} for {persona}.",
    "Digitized microfiche from {organization} shows {persona} beside {cue} {value}.",
    "Skewed page: {cue} {value} ... rest illegible ... signed {persona}.",
    "Auto-capture summary - {persona}; {cue}; {value}; confidence low.",
    "The flatbed scan of the {organization} form yields {cue}: {value} ({persona}).",
    "Line 7 recognized as: {value} under {cue}, subject {persona}.",
    "Despite smudges, the {cue} for {persona} resolves to {value}.",
    "Photocopy artifacts aside, {cue} {value} is attributed to {persona}.",
    "OCR pass two agrees: {persona}, {cue}, {value}.",
    "Extracted fields - name {persona} | {cue} {value} | source {organization}.",
    "Torn corner; surviving text pairs {value} with the {cue} of {persona}.",
    "Handwriting recognition guessed {value} for the {cue} on {persona}'s sheet.",
    "The faxed copy from {organization} still shows {cue} {value} for {persona}.",
    "Character read errors possible: {cue} tentatively {value}, holder {persona}.",
    "Batch scan 12: {persona} -> {cue} -> {value}.",
    "Deskewed image confirms the {cue} field contains {value} ({persona}).",
    "Legibility 62%: {cue} {value}; subject line names {persona}.",
    "From the stained intake sheet: {persona}, {cue} {value}.",
    "Second reviewer typed {value} for the {cue} after zooming on {persona}'s form.",
    "The capture tool split the {cue} of {persona} across lines as {value}.",
    "Scanner output for {organization} lot 4: {cue}={value}, person {persona}.",
    "Ink bleed obscured headers, yet {value} stands under {cue} for {persona}.",
    "Final OCR verdict: field {cue}, content {value}, name {persona}.",
)
_add(
    "spoken",
    "positive",
    "The speaker for {persona} read the {cue} aloud as {value}.",
    "Transcript: for {persona}, the {cue} was spoken as {value}.",
    "A synthetic voice note from {organization} gives {value} for the {cue}.",
    "The caller carefully spelled {persona}'s {cue}: {value}.",
    "Transcribed audio says the {cue} associated with {persona} is {value}.",
    "In the rehearsal recording, {value} is stated as the {cue}.",
    "Minute 3 of the call: {persona} dictates the {cue} as {value}.",
    "Voicemail left at {organization}: my {cue} is {value}, this is {persona}.",
    "The agent repeated the {cue} back to {persona} as {value}.",
    "Dictation log - {persona} pronounces the {cue}: {value}.",
    "On speakerphone, {persona} confirmed {value} for the {cue}.",
    "Meeting audio captures {persona} stating the {cue}, namely {value}.",
    "The interpreter relayed {persona}'s {cue} to {organization} as {value}.",
    "Podcast-style demo: host reads the {cue} of {persona}, {value}.",
    "Caller ID matched {persona}; the stated {cue} was {value}.",
    "Slowly and twice, {persona} spelled out the {cue}: {value}.",
    "The transcription service returned {value} as {persona}'s {cue}.",
    "Audio QA note: {cue} audible at 00:42 as {value}, speaker {persona}.",
    "During the drill, staff at {organization} recited {cue} {value} for {persona}.",
    "The recorded prompt asks {persona} to confirm the {cue} {value}.",
    "Live captioning displayed {value} when {persona} said the {cue}.",
    "In the roleplay call, the {cue} given by {persona} sounds like {value}.",
    "Phone notes: {persona} - {cue} - {value} - call ended.",
    "The read-back check with {organization} settled the {cue} at {value}.",
    "Whispered but audible, {persona} gave the {cue} as {value}.",
    "Voice memo three: {cue} of {persona} equals {value}.",
    "The operator keyed {value} while {persona} spoke the {cue}.",
    "Interview tape: {persona} answers the {cue} question with {value}.",
    "Simulated hotline audio pairs {persona} with {cue} {value}.",
    "After a pause, {persona} restated the {cue} clearly: {value}.",
)
_add(
    "mixed_entity",
    "positive",
    "{persona}'s {cue} is {value}; the separate {other_cue} is {other_value}.",
    "At {organization}, {other_cue} {other_value} and {cue} {value} belong to {persona}.",
    "Two synthetic fields were supplied: {cue}={value}, {other_cue}={other_value}.",
    "The form for {persona} lists {other_value} under {other_cue} and {value} under {cue}.",
    "Cross-check {cue} {value} against {other_cue} {other_value} for {persona}.",
    "A mixed record from {organization} contains {value} ({cue}) and {other_value} ({other_cue}).",
    "Both entries arrived together: {persona}'s {cue} {value} and {other_cue} {other_value}.",
    "Intake captured {cue}: {value}, then {other_cue}: {other_value}, same person {persona}.",
    "{organization} stores two fields for {persona} - {cue} {value}; {other_cue} {other_value}.",
    "Do not confuse the {cue} {value} with the {other_cue} {other_value} of {persona}.",
    "Line one gives {value} as {cue}; line two gives {other_value} as {other_cue} ({persona}).",
    "The combined summary pairs {cue} {value} with {other_cue} {other_value} for {persona}.",
    "For {persona}, reviewers matched {value} to {cue} and {other_value} to {other_cue}.",
    "Dual entry: {cue} -> {value}; {other_cue} -> {other_value}; subject {persona}.",
    "{persona} presented documents bearing {cue} {value} and {other_cue} {other_value}.",
    "Copy A shows the {cue} {value}; copy B adds {other_cue} {other_value} for {persona}.",
    "Two headings, one subject: {cue} {value} and {other_cue} {other_value}, {persona}.",
    "{organization} merged files so {persona} carries {value} ({cue}) plus {other_value} "
    "({other_cue}).",
    "Checklist done: {cue} recorded as {value}; {other_cue} recorded as {other_value} ({persona}).",
    "The envelope held both the {cue} {value} and the {other_cue} {other_value} of {persona}.",
    "Field pair for {persona}: primary {cue} {value}, secondary {other_cue} {other_value}.",
    "Verification used {other_cue} {other_value} alongside {cue} {value} for {persona}.",
    "One sheet, two values: {value} as {cue}, {other_value} as {other_cue} - {persona}.",
    "Clerks at {organization} keyed {cue} {value} before {other_cue} {other_value} for {persona}.",
    "Profile update: {persona} now shows {cue} {value} and {other_cue} {other_value}.",
    "Neither field is blank: {cue} {value}; {other_cue} {other_value}; holder {persona}.",
    "The audit trail for {persona} logs {value} under {cue}, then {other_value} under "
    "{other_cue}.",
    "Registration bundled the {cue} {value} with the {other_cue} {other_value} ({persona}).",
    "Separate columns keep {cue} {value} apart from {other_cue} {other_value} for {persona}.",
    "Final review: {persona}, {cue} {value}, {other_cue} {other_value}, no conflicts.",
)
_add(
    "cue_free",
    "positive",
    "The synthetic identity entry for {persona} contains {value}.",
    "{organization} stored {value} in the fictional identity section for {persona}.",
    "For {persona}, the identity form shows {value} without a field heading.",
    "The unlabeled synthetic entry associated with {persona} is {value}.",
    "An identity worksheet from {organization} contains the entry {value}.",
    "The fictional subject {persona} is linked to the unlabeled entry {value}.",
    "Somewhere in the paperwork of {persona}, {value} appears on its own line.",
    "{value} sits unexplained in the margin of {persona}'s intake sheet.",
    "A sticky note on the folder of {persona} reads only {value}.",
    "The email body sent to {organization} contains just {persona} and {value}.",
    "Free-text comment: {persona} ... {value} ... no heading given.",
    "Under miscellaneous, the file of {persona} lists {value}.",
    "{organization} found {value} scribbled beside the name {persona}.",
    "No column label survives, but the cell next to {persona} holds {value}.",
    "The chat log shows {persona} pasting {value} without further comment.",
    "An untitled attachment pairs {persona} with {value}.",
    "Line four of the memo about {persona} is simply {value}.",
    "Within the note, {value} follows the greeting to {persona} directly.",
    "The plain-text export for {persona} carries {value} in the body.",
    "Someone typed {value} into the notes field of {persona}'s profile.",
    "The whiteboard photo from {organization} shows {persona} then {value}.",
    "Handwritten at the bottom of {persona}'s page: {value}.",
    "{value} appears mid-paragraph in the summary about {persona}.",
    "The draft about {persona} was saved with {value} still embedded.",
    "Loose sheet: {persona} on the first line, {value} on the second.",
    "In the backup dump from {organization}, {persona} sits one row above {value}.",
    "The ticket description mentions {persona} and later {value}, nothing more.",
    "A copied sentence about {persona} ends abruptly with {value}.",
    "Between two blank lines in {persona}'s file, {value} stands alone.",
    "The migration log for {organization} pairs {persona} with the bare string {value}.",
)
_add(
    "cue_shape_conflict",
    "positive",
    "Ignore the identifier shape: {persona}'s {cue} is explicitly {value}.",
    "The heading controls classification; {cue} for {persona} is {value}.",
    "Although the shape is shared, {organization} labels {value} as the {cue}.",
    "Treat {value} according to its field name, {cue}, for {persona}.",
    "This contrastive example assigns {value} to {cue}, independent of appearance.",
    "The synthetic form states {cue}: {value}; morphology alone is ambiguous.",
    "Despite looking like another code, {value} is the {cue} of {persona}.",
    "Read the label, not the letters: {cue} - {value} ({persona}).",
    "{organization} instructs staff to file {value} under {cue} regardless of format.",
    "The printed heading beats the pattern: {value} counts as {cue} for {persona}.",
    "Field name wins here; {persona} registered {value} as the {cue}.",
    "Visually similar codes abound, yet this {value} is declared the {cue}.",
    "Classification note: {value} belongs to {cue}, per the form of {persona}.",
    "Per policy at {organization}, the {cue} column defines {value}, not its shape.",
    "Even if the format suggests otherwise, {persona} filed {value} as {cue}.",
    "The annotation guide says: when headed {cue}, {value} is that field.",
    "Shape is misleading; the ledger marks {value} as the {cue} of {persona}.",
    "Trust the caption - {cue}: {value} - signed {persona}.",
    "For grading purposes, {value} beneath the {cue} banner keeps that meaning.",
    "{organization} confirmed the heading {cue} applies to {value} for {persona}.",
    "Contrary to its look, {value} was entered in the {cue} box by {persona}.",
    "The desk manual repeats: honor the {cue} heading; here it covers {value}.",
    "Row label {cue} governs; the cell content is {value} ({persona}).",
    "Auditors accepted {value} as {cue} because the form of {persona} says so.",
    "Same alphabet, different field: this {value} is the {cue} of {persona}.",
    "The stamped heading {cue} fixes the meaning of {value} at {organization}.",
    "Do not reclassify by pattern; {persona} declared {value} to be the {cue}.",
    "Under the bold {cue} caption sits {value}, whatever it resembles.",
    "The intake wizard forced {value} into the {cue} slot for {persona}.",
    "Format lookalikes exist, but the {cue} entry of {persona} reads {value}.",
)
_add(
    "near_miss",
    "hard_negative",
    "The warehouse ticket {negative_value} was assigned to {persona}.",
    "{organization} shipped the parcel under tracking label {negative_value}.",
    "Build {negative_value} completed in the demonstration environment.",
    "The maintenance request {negative_value} concerns a training laptop.",
    "A fictional invoice uses {negative_value} as its non-personal document number.",
    "The library shelf tag {negative_value} appears beside {persona}'s checkout note.",
    "Support case {negative_value} tracks a printer jam at {organization}.",
    "Deployment {negative_value} rolled back cleanly last night.",
    "The cafeteria order slip prints {negative_value} in the corner.",
    "Purchase order {negative_value} covers ten demo chairs for {organization}.",
    "{persona} quoted job number {negative_value} when calling facilities.",
    "The elevator inspection sticker shows permit {negative_value}.",
    "Batch {negative_value} finished the nightly test run without errors.",
    "Conference room booking {negative_value} was cancelled by {persona}.",
    "The courier manifest lists crate {negative_value} for the loading dock.",
    "Work order {negative_value} schedules a lightbulb swap at {organization}.",
    "Release candidate {negative_value} passed the smoke suite.",
    "The parking validation stub carries serial {negative_value}.",
    "Helpdesk ticket {negative_value} mentions a flickering monitor for {persona}.",
    "Shipment {negative_value} clears customs in the training scenario.",
    "The recycled badge printer test emitted sample {negative_value}.",
    "Inventory sweep found asset sticker {negative_value} on a demo desk.",
    "Change request {negative_value} was approved at the {organization} standup.",
    "The projector bulb order cites {negative_value} internally.",
    "Sprint task {negative_value} moved to done this morning.",
    "A demo receipt prints {negative_value} above the fictional total.",
    "The loaner laptop label reads {negative_value}, checked out by {persona}.",
    "Freight quote {negative_value} expires at the end of the demo.",
    "{organization} archived RFQ {negative_value} after the mock bid closed.",
    "The training queue shows job {negative_value} still pending.",
)
_add(
    "placeholder",
    "hard_negative",
    "Leave the identity field as {{SYNTHETIC_IDENTIFIER}} until test data is generated.",
    "Documentation placeholder: FICTIONAL-ID-GOES-HERE.",
    "The blank form displays [IDENTIFIER NOT PROVIDED].",
    "Template text only: ENTER A SYNTHETIC VALUE HERE.",
    "No value is present; the example contains the token {{DATE_PLACEHOLDER}}.",
    "The mock screen shows an empty identifier slot, not a person's value.",
    "Replace {{SAMPLE_CODE}} before publishing the walkthrough.",
    "The tutorial keeps YOUR-ID-HERE where a real entry would sit.",
    "Field left intentionally blank pending synthetic generation.",
    "The stub record for {persona} still reads TBD in every column.",
    "Insert a generated string at the marker {{FILL_ME}} later.",
    "This wireframe from {organization} uses lorem text and an empty box.",
    "The demo slide shows XXXX-XXXX where an entry would appear.",
    "Awaiting fixtures: the cell holds the word PENDING only.",
    "A gray hint reads: type the sample entry here.",
    "The form preview renders {{IDENTITY_STUB}} in italics.",
    "Nothing was entered; the draft keeps the caption EXAMPLE ONLY.",
    "QA left the note: populate with generated data before review.",
    "The onboarding doc says to paste a placeholder, never a real entry.",
    "Mock printout: name {persona}, value column empty.",
    "The sandbox at {organization} seeds every field with NULL.",
    "Curly-brace tokens like {{DEMO_FIELD}} remain unresolved.",
    "Screenshot two shows the unfilled entry box outlined in red.",
    "The sample contract keeps ______ where a code would go.",
    "Trainer instructions: leave the slot blank during the dry run.",
    "The CSV template ships with the header only, no rows.",
    "A watermark says SPECIMEN across the empty field.",
    "The e-form rejects submission until the placeholder is replaced.",
    "Draft copy for {organization} repeats the token {{TO_BE_GENERATED}}.",
    "The printed guide leaves a dotted line for the future entry.",
)
_add(
    "negation",
    "hard_negative",
    "Do not place personal identifiers in this demonstration note.",
    "{persona} confirmed that no identity value was included.",
    "The hypothetical form would request an identifier, but it remains blank.",
    "{organization} removed the sensitive field before creating this example.",
    "If a credential existed it would be redacted; this sentence contains none.",
    "The reviewer wrote that no birth information should appear here.",
    "Nothing resembling a personal code was entered by {persona}.",
    "The demo policy forbids storing real entries; none are present.",
    "Had there been a value, {organization} would have masked it.",
    "This paragraph deliberately omits any identifying string.",
    "No number follows the colon: the line was scrubbed.",
    "{persona} declined to provide the optional field, so it stays empty.",
    "The redaction pass removed every candidate token from this note.",
    "Suppose a code were present; the checklist would still hide it.",
    'The empty quotes below illustrate an absent entry: "".',
    "Compliance confirmed the export from {organization} contains no personal data.",
    "There is no entry to read here, only this explanatory sentence.",
    "The trainer repeated: never paste genuine values into the sandbox.",
    "A dash marks the removed field on {persona}'s printout.",
    "Auditors verified that the sample lacks any identifier whatsoever.",
    "Should one appear, delete it; today the section is clear.",
    "The mock message ends without disclosing anything about {persona}.",
    "Every sensitive cell was blanked before {organization} shared the sheet.",
    "Not a single code survived the anonymization drill.",
    "The absence itself is the lesson: this record holds nothing sensitive.",
    "In this counterfactual, the identifier was never issued to {persona}.",
    "The template ships empty by design, as {organization} requires.",
    "Reviewers found zero personal strings in the attached example.",
    "No, the field was not completed, and it will remain blank.",
    "This negative sample proves a sentence can mention forms yet reveal nothing.",
)
_add(
    "unrelated_shape",
    "hard_negative",
    "The asset label {negative_value} identifies a synthetic printer, not a person.",
    "Use {negative_value} as the test batch code for {organization}.",
    "The non-personal catalog number is {negative_value}.",
    "A demo vehicle part carries stock code {negative_value}.",
    "The queue item {negative_value} belongs to a software job.",
    "{negative_value} is a fictional product tag unrelated to identity.",
    "Firmware image {negative_value} flashed onto the training router.",
    "The seed packet in the lobby garden is lot {negative_value}.",
    "Museum exhibit tag {negative_value} hangs on the model engine.",
    "{organization} stamps loaner cables with code {negative_value}.",
    "The board game copy in the break room is numbered {negative_value}.",
    "Test tube rack {negative_value} holds only colored water.",
    "The projector in room four reports serial {negative_value}.",
    "Sample SKU {negative_value} maps to a cardboard demo box.",
    "Wristband {negative_value} admits {persona} to the mock conference.",
    "The stage prop crate is labeled {negative_value} in chalk.",
    "Router config backup {negative_value} lives on the lab share.",
    "A 3D-printed bracket carries part number {negative_value}.",
    "The coffee machine descaling kit is order {negative_value}.",
    "Bicycle rack permit {negative_value} covers the courtyard.",
    "{organization} catalogs the demo drone as unit {negative_value}.",
    "Paint swatch {negative_value} matches the training room wall.",
    "The fire drill clipboard lists checkpoint {negative_value}.",
    "Loaner headset {negative_value} sits in the AV cabinet.",
    "Greenhouse sensor {negative_value} logs humidity for the plant demo.",
    "The mock warehouse bin {negative_value} stores foam bricks.",
    "Slide deck template {negative_value} ships with the brand kit.",
    "Elevator car B bears inspection plate {negative_value}.",
    "The test signage order confirms placard {negative_value} for {organization}.",
    "Prop currency bundle {negative_value} is clearly marked specimen.",
)
_add(
    "documentation_meta",
    "hard_negative",
    "The manual describes a field named {cue} but supplies no example value.",
    "Schema note: {cue} is an optional string in user-provided datasets.",
    "This documentation discusses {cue} detection without containing a record.",
    "A tutorial heading mentions {cue}; the sample cell is deliberately empty.",
    "The format guide names {cue} only as metadata.",
    "The contributor note asks how {cue} annotations should be represented.",
    "Release notes mention stricter validation of the {cue} column.",
    "The API reference marks {cue} as nullable and gives no sample.",
    "Chapter two explains why the {cue} field exists at all.",
    "A changelog entry renames the {cue} heading across templates.",
    "The style guide capitalizes {cue} consistently in prose.",
    "Reviewers at {organization} debated the wording of the {cue} tooltip.",
    "The FAQ clarifies that {cue} entries are optional in demos.",
    "Slide six defines the {cue} concept without showing data.",
    "The data dictionary lists {cue} with type string and no default.",
    "An RFC proposes deprecating the {cue} column next quarter.",
    "The glossary cross-links {cue} to its parent section.",
    "Training materials from {organization} cover the {cue} workflow abstractly.",
    "The lint rule warns when {cue} appears unlabeled in configs.",
    "Docs bug: the {cue} description repeats a paragraph twice.",
    "The migration guide says {cue} moves to the new schema untouched.",
    "A code comment explains parsing of the {cue} attribute.",
    "The onboarding wiki defines {cue} in a single sentence.",
    "Localization review flagged the {cue} label for translation.",
    "The spec forbids examples inside the {cue} subsection.",
    "Version 2 of the handbook shortens the {cue} chapter.",
    "An architecture diagram labels one box simply {cue}.",
    "The test plan enumerates edge cases for the {cue} parser.",
    "Editors at {organization} approved the reworded {cue} paragraph.",
    "The template README tells writers to leave {cue} sections empty.",
)
_add(
    "adjacent_value",
    "hard_negative",
    "Near the blank identity field, the page number is {negative_value}.",
    "{persona}'s form has no identity value; {negative_value} is the room code.",
    "The date field is empty, while {negative_value} identifies the document revision.",
    "{organization} left the sensitive cell blank beside batch {negative_value}.",
    "The adjacent value {negative_value} is a harmless routing label.",
    "No personal value appears; {negative_value} is merely the test row number.",
    "Beside the redacted box, footer code {negative_value} remains visible.",
    "The empty column sits next to shelf mark {negative_value}.",
    "Printer margin note {negative_value} appears under the blank entry.",
    "{persona} left the main field empty; the corner shows {negative_value}.",
    "Only the binder index {negative_value} survives on this page.",
    "The cleared cell neighbors the version stamp {negative_value}.",
    "Next to the struck-through entry, {organization} printed {negative_value}.",
    "A staple covers the blank; the visible code is {negative_value}.",
    "Row 9 is empty; row 10 carries the harmless tag {negative_value}.",
    "The wiped field borders the shipment lane code {negative_value}.",
    "Under the empty heading, the photocopier added {negative_value}.",
    "The masked area sits above the form batch {negative_value}.",
    "{persona} sees only the queue position {negative_value} beside the void cell.",
    "In the scanned copy, the blank slot touches watermark {negative_value}.",
    "The vacated entry line ends near locker tag {negative_value}.",
    "Nothing sensitive here - the neighboring sticker reads {negative_value}.",
    "The obscured entry's neighbor is the aisle marker {negative_value}.",
    "Beneath the erased field, {organization} stamped {negative_value}.",
    "The intentionally empty box aligns with page tab {negative_value}.",
    "Blank on the left, benign on the right: {negative_value}.",
    "Only formatting remains, plus the layout grid code {negative_value}.",
    "The redraft dropped the entry; the draft number {negative_value} stayed.",
    "{persona}'s cleared row abuts the printer tray code {negative_value}.",
    "The removed entry's slot points to filing lane {negative_value}.",
)
